Repository commclassroom/roadmaps, pull requests merged in 2022-08, with the labels that each got.

#66 Added GitVio to Open-Source
  Open-Source/Contribute/Readme.md
Labels: Under Evaluation, Approved but conflict

#73 Corrected the anchor text in communities section.
  DevOps/Communities/Readme.md
Labels: Under Evaluation

#57 Removed Unavailable Jobs
  Open-Source/Job-Boards/Readme.md
Labels: Approved but conflict

#50 GSoC All Front end Projects
  Frontend-Development/Contribute/Readme.md
Labels: Under Evaluation

#61 Fix typo
  README.md
Labels: documentation, Under Evaluation

#97 feat: Add Blockchain — Communities, Projects, Job Boards
  Blockchain/Communities/README.md
  Blockchain/Contribute/README.md
  Blockchain/Job-Boards/README.md
Labels: Approved but later

#60 Added React play to contributors
  Frontend-Development/Contribute/Readme.md
Labels: Under Evaluation, Approved but conflict

#38 Issues and PR templates added
  .github/ISSUE_TEMPLATE/Bug.yml
  .github/ISSUE_TEMPLATE/Feature.yml
  .github/ISSUE_TEMPLATE/Other.yml
  .github/Pull_request_template.md
Labels: Under Evaluation

#81 added algebra-for-you
  Open-Source/Contribute/Readme.md
Labels: Under Evaluation, Approved but conflict

#151 Added Remix project in Open source projects.
  Blockchain/Contribute/README.md
Labels: Under Evaluation

#154 Update Readme.md
  Blockchain/Contribute/README.md
Labels: Under Evaluation

#130 Add Remote3 and UseWeb3
  Blockchain/Job-Boards/README.md
Labels: Under Evaluation
